"""Pydantic models for the Supply Chain Digital Twin system."""

from enum import Enum
from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field


class SeverityLevel(str, Enum):
    """Severity levels for disruption events."""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class RouteEdge(BaseModel):
    """Represents an edge in the supply chain graph."""
    source: str = Field(..., description="Source node")
    target: str = Field(..., description="Target node")
    time_days: float = Field(..., ge=0, description="Transit time in days")
    cost_usd: float = Field(..., ge=0, description="Cost in USD")
    carbon_tons: float = Field(..., ge=0, description="Carbon footprint in tons")
    
    model_config = {
        "json_schema_extra": {
            "example": {
                "source": "shanghai",
                "target": "suez_canal",
                "time_days": 7.5,
                "cost_usd": 15000,
                "carbon_tons": 280
            }
        }
    }


class DisruptionEvent(BaseModel):
    """Represents a supply chain disruption event."""
    event_id: str = Field(..., description="Unique event identifier")
    event_type: str = Field(..., description="Type of disruption")
    severity: SeverityLevel = Field(..., description="Severity level")
    affected_nodes: List[str] = Field(..., description="List of affected node IDs")
    description: str = Field(..., description="Event description")
    timestamp: str = Field(..., description="Event timestamp")
    
    model_config = {
        "json_schema_extra": {
            "example": {
                "event_id": "evt_001",
                "event_type": "canal_blockage",
                "severity": "critical",
                "affected_nodes": ["suez_canal"],
                "description": "Suez Canal Blocked due to grounding incident",
                "timestamp": "2024-01-15T08:30:00Z"
            }
        }
    }


class CascadeRiskReport(BaseModel):
    """Report generated by the Simulator agent."""
    simulation_count: int = Field(..., ge=1, description="Number of Monte Carlo simulations run")
    affected_routes: List[Dict[str, Any]] = Field(..., description="Routes affected by disruption")
    cascade_delays: Dict[str, float] = Field(..., description="Predicted delays per route segment")
    risk_level: SeverityLevel = Field(..., description="Overall risk level")
    recommended_action: str = Field(..., description="Recommended mitigation action")
    alternative_paths: List[List[str]] = Field(default_factory=list, description="Alternative route paths")
    confidence_score: float = Field(..., ge=0, le=1, description="Confidence in predictions")
    
    model_config = {
        "json_schema_extra": {
            "example": {
                "simulation_count": 1000,
                "affected_routes": [{"path": ["shanghai", "suez_canal", "rotterdam"], "delay_days": 14}],
                "cascade_delays": {"shanghai_rotterdam": 14.5},
                "risk_level": "high",
                "recommended_action": "Re-route via Cape of Good Hope",
                "alternative_paths": [["shanghai", "cape_of_good_hope", "rotterdam"]],
                "confidence_score": 0.87
            }
        }
    }


class RoutePlan(BaseModel):
    """Optimized route plan from the Optimizer agent."""
    route_path: List[str] = Field(..., description="Ordered list of nodes in the route")
    total_time_days: float = Field(..., ge=0, description="Total transit time in days")
    total_cost_usd: float = Field(..., ge=0, description="Total cost in USD")
    total_carbon_tons: float = Field(..., ge=0, description="Total carbon footprint in tons")
    weighted_score: float = Field(..., description="Multi-objective optimization score")
    edges: List[RouteEdge] = Field(default_factory=list, description="Route edges")
    is_alternative: bool = Field(default=False, description="Whether this is an alternative route")
    budget_multiplier: float = Field(default=1.0, ge=1.0, description="Budget constraint multiplier")
    
    model_config = {
        "json_schema_extra": {
            "example": {
                "route_path": ["shanghai", "cape_of_good_hope", "rotterdam", "chicago"],
                "total_time_days": 28.0,
                "total_cost_usd": 45000,
                "total_carbon_tons": 890,
                "weighted_score": 0.72,
                "edges": [],
                "is_alternative": True,
                "budget_multiplier": 1.0
            }
        }
    }


class NegotiationResult(BaseModel):
    """Result from the Negotiator agent."""
    success: bool = Field(..., description="Whether negotiation was successful")
    route_plan: Optional[RoutePlan] = Field(default=None, description="Confirmed route plan")
    failure_reason: Optional[str] = Field(default=None, description="Reason for failure if any")
    retry_count: int = Field(default=0, ge=0, description="Number of retry attempts")
    carrier_response: Optional[Dict[str, Any]] = Field(default=None, description="Carrier API response")
    
    model_config = {
        "json_schema_extra": {
            "example": {
                "success": True,
                "route_plan": {"route_path": ["shanghai", "rotterdam"], "total_time_days": 25},
                "failure_reason": None,
                "retry_count": 0,
                "carrier_response": {"booking_id": "BK123456"}
            }
        }
    }


class AgentState(BaseModel):
    """Main state object for the LangGraph workflow."""
    disruption_event: Optional[DisruptionEvent] = Field(default=None, description="Current disruption event")
    cascade_report: Optional[CascadeRiskReport] = Field(default=None, description="Simulation results")
    route_plan: Optional[RoutePlan] = Field(default=None, description="Optimized route")
    negotiation_result: Optional[NegotiationResult] = Field(default=None, description="Negotiation outcome")
    retry_count: int = Field(default=0, ge=0, description="Total retry count")
    max_retries: int = Field(default=3, ge=1, description="Maximum retry attempts")
    current_step: str = Field(default="ingestor", description="Current workflow step")
    workflow_log: List[str] = Field(default_factory=list, description="Log of workflow events")
    graph_data: Optional[Dict[str, Any]] = Field(default=None, description="Serialized graph data")
    
    model_config = {
        "json_schema_extra": {
            "example": {
                "disruption_event": {"event_id": "evt_001", "severity": "critical"},
                "cascade_report": {"simulation_count": 1000, "risk_level": "high"},
                "route_plan": {"route_path": ["shanghai", "rotterdam"], "total_cost_usd": 45000},
                "negotiation_result": {"success": True},
                "retry_count": 0,
                "max_retries": 3,
                "current_step": "optimizer",
                "workflow_log": ["Started workflow", "Ingested event"],
                "graph_data": {"nodes": ["shanghai", "rotterdam"], "edges": []}
            }
        }
    }
    
    def add_log(self, message: str) -> None:
        """Add a log entry to the workflow log."""
        self.workflow_log.append(message)
    
    def increment_retry(self) -> None:
        """Increment the retry count."""
        self.retry_count += 1
    
    def can_retry(self) -> bool:
        """Check if more retries are allowed."""
        return self.retry_count < self.max_retries
